# File konfigurasi untuk Netlify

[build]
  # Direktori tempat file-file publik Anda berada (index.html, dll.)
  # Karena file-file tersebut ada di root, kita bisa gunakan "."
  publish = "."
  
  # Direktori tempat serverless functions Anda berada
  functions = "netlify/functions"

# Pengaturan untuk server development lokal (opsional, tapi berguna)
[dev]
  # Port default untuk `netlify dev`
  port = 8888
  publish = "."
  functions = "netlify/functions"

# Aturan redirect agar fungsi bisa diakses dengan mudah
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
